routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\StandingsController;
use App\Http\Controllers\MatchController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/master', function () {
    return view('layouts.master');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/clubs', ClubController::class);
Route::resource('/scores', ScoreController::class);
Route::get('/standings', [StandingsController::class, 'index'])->name('standings.index');
Route::get('/matches/create', [MatchController::class, 'create'])->name('matches.create');
Route::resource('/matches', MatchController::class);
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');

resources/views/home.blade.php
@extends('layouts.content')

@section('title', 'Dashboard')

@section('content')

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="mb-4">Menu</h2>
            <div class="list-group">
                <a href="{{ route('clubs.index') }}" class="list-group-item list-group-item-action">View Club</a>
                
                <a href="{{ route('matches.index') }}" class="list-group-item list-group-item-action">View Match</a>
                
                <a href="{{ route('standings.index') }}" class="list-group-item list-group-item-action">View Standings</a>
                
                <a href="{{ route('clubs.create') }}" class="list-group-item list-group-item-action">Create Club</a>
                
                <a href="{{ route('matches.create') }}" class="list-group-item list-group-item-action">Create Match</a>
            </div>
        </div>
    </div>
</div>

@endsection