routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\StandingsController;
use App\Http\Controllers\MatchController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/master', function () {
    return view('layouts.master');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/clubs', ClubController::class);
Route::resource('/scores', ScoreController::class);
Route::get('/standings', [StandingsController::class, 'index'])->name('standings.index');
Route::get('/matches/create', [MatchController::class, 'create'])->name('matches.create');
Route::resource('/matches', MatchController::class);
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');

app/Models/Score.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Score extends Model
{
    protected $fillable = [
    'club1_id',
    'club2_id',
    'match_played',
    'match_win',
    'match_lose',
    'match_draw',
    'goals_match_win',
    'goals_match_lose',
    'points',
];

    public function club1()
    {
        return $this->belongsTo(Club::class, 'club1_id');
    }

    public function club2()
    {
        return $this->belongsTo(Club::class, 'club2_id');
    }
}

app/Http/Controllers/ScoreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Score;
use App\Models\Club;
use Illuminate\Support\Facades\Validator;

class ScoreController extends Controller
{
    public function index()
    {
        $scores = Score::all();
        return view('scores.index', compact('scores'));
    }

    public function create()
    {
        $clubs = Club::all();
        return view('scores.create', compact('clubs'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'club1' => 'required|different:club2',
            'club2' => 'required',
            'match_played' => 'required|numeric',
            'match_win' => 'required|numeric',
            'match_lose' => 'required|numeric',
            'match_draw' => 'required|numeric',
            'goals_match_win' => 'required|numeric',
            'goals_match_lose' => 'required|numeric',
        ]);

        $score = new Score();
        $score->club1_id = $request->input('club1');
        $score->club2_id = $request->input('club2');
        $score->played = $request->input('played');
        $score->match_win = $request->input('won');
        $score->match_draw = $request->input('drawn');
        $score->match_lst = $request->input('lost');
        $score->goals_for = $request->input('goals_for');

        $score->save();

        return redirect()->route('scores.index')->with('success', 'Score created successfully');
    }

    public function show($id)
    {
        $score = Score::findOrFail($id);
        return view('scores.show', compact('score'));
    }

    public function edit($id)
    {
        $score = Score::findOrFail($id);
        $clubs = Club::all();
        return view('scores.edit', compact('score', 'clubs'));
    }
    
    public function update(Request $request, $id)
    {
        $score = Score::findOrFail($id);
        $score->update($request->all());
    
        return redirect()->route('scores.index')->with('success', 'Score updated successfully');
    }

    public function destroy($id)
    {
        $score = Score::findOrFail($id);
        $score->delete();

        return redirect()->route('scores.index')->with('success', 'Score deleted successfully');
    }
}

resources/views/scores/create.blade.php
@extends('layouts.content')

@section('content')

    <div class="container">
        <h1>Add Score</h1>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('scores.store') }}" method="POST">
            @csrf

            <div class="form-group">
                <label for="club_id">Club:</label>
                <select name="club_id" class="form-control">
                    @foreach ($clubs as $club)
                        <option value="{{ $club->id }}">{{ $club->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="played">Match Played:</label>
                <input type="number" name="match_played" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="won">Match Win:</label>
                <input type="number" name="match_win" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="lost">Match Lose:</label>
                <input type="number" name="match_lose" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="drawn">Match Draw:</label>
                <input type="number" name="match_draw" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="goals_for">Goals When Match Win:</label>
                <input type="number" name="goals_match_win" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="goals_against">Goals When Match Lose:</label>
                <input type="number" name="goals_match_lose" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="points">Points:</label>
                <input type="number" name="points" class="form-control" required>
            </div>

            <button type="submit" class="btn btn-primary">Add Score</button>
        </form>
    </div>
@endsection

resources/views/scores/edit.blade.php
@extends('layouts.content')

@section('content')

<div class="container">
    <h1>Edit Score</h1>
    <form action="{{ route('scores.update', $score->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="club_id">Club Name:</label>
            <input type="text" value="{{ $score->club->name }}" class="form-control" readonly>
        </div>

        <div class="form-group">
            <label for="match_played">Match Played</label>
            <input type="number" name="match_played" value="{{ $score->match_played }}" class="form-control">
        </div>

        <div class="form-group">
            <label for="match_win">Match Win:</label>
            <input type="number" name="match_win" value="{{ $score->match_win }}" class="form-control">
        </div>

        <div class="form-group">
            <label for="match_lose">Match Lose:</label>
            <input type="number" name="match_lose" value="{{ $score->match_lose }}" class="form-control">
        </div>

        <div class="form-group">
            <label for="match_draw">Match Draw:</label>
            <input type="number" name="match_draw" value="{{ $score->match_draw }}" class="form-control">
        </div>

        <div class="form-group">
            <label for="goals_match_win">Goals When Match Win:</label>
            <input type="number" name="goals_match_win" value="{{ $score->goals_match_win }}" class="form-control">
        </div>

        <div class="form-group">
            <label for="goals_match_lose">Goals When Match Lose:</label>
            <input type="number" name="goals_match_lose" value="{{ $score->goals_match_lose }}" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary">Update Score</button>
    </form>
</div>

@endsection

resources/views/scores/index.blade.php
@extends('layouts.content')


@section('content')

<div class="container">
    <h1>Scores</h1>
    <a href="{{ route('scores.create') }}" class="btn btn-primary mb-3">Add Score</a>

    @if($scores->isEmpty())
        <p>No scores available.</p>
    @else
        <table class="table">
            <thead>
                <tr>
                    <th>Club Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($scores as $score)
                    <tr>
                        <td>{{ $score->club->name }}</td>
                        <td>
                            <a href="{{ route('scores.show', $score->id) }}" class="btn btn-sm btn-info">View</a>
                            <a href="{{ route('scores.edit', $score->id) }}" class="btn btn-sm btn-primary">Edit</a>
                            <form action="{{ route('scores.destroy', $score->id) }}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this score?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif
</div>

@endsection

resources/views/scores/show.blade.php
@extends('layouts.content')

@section('content')

    <div class="container">
        <h1>Score Details</h1>

        <div class="card">
            <div class="card-body">
                <p class="card-text"><strong>Club Name : </strong> {{ $score->club->name }}</p>
                <p class="card-text"><strong>Match Played: </strong> {{ $score->match_played }}</p>
                <p class="card-text"><strong>Match Win : </strong> {{ $score->match_win }}</p>
                <p class="card-text"><strong>Match Lose : </strong> {{ $score->match_lose }}</p>
                <p class="card-text"><strong>Match Draw :</strong> {{ $score->match_draw }}</p>
                <p class="card-text"><strong>Goals When Match Win: </strong> {{ $score->goals_match_win }}</p>
                <p class="card-text"><strong>Goals When Match Lose : </strong> {{ $score->goals_match_lose }}</p>
                <p class="card-text"><strong>Points : </strong> {{ $score->points }}</p>
                
                <a href="{{ url()->previous() }}" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>

@endsection