routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\StandingsController;
use App\Http\Controllers\MatchController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/master', function () {
    return view('layouts.master');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/clubs', ClubController::class);
Route::resource('/scores', ScoreController::class);
Route::get('/standings', [StandingsController::class, 'index'])->name('standings.index');
Route::get('/matches/create', [MatchController::class, 'create'])->name('matches.create');
Route::resource('/matches', MatchController::class);
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');

app/Models/Club.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Club extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'city'];
}

app/Http/Controllers/ClubController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Club;
use App\Models\Score;
use Illuminate\Support\Facades\Validator;

class ClubController extends Controller
{
    public function index()
    {
        $clubs = Club::all();
        return view('clubs.index', compact('clubs'));
    }

    public function create()
    {
        return view('clubs.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:clubs,name,' . $request->id,
            'city' => 'required',
        ], [
            'name.unique' => 'Club is already exist.',
        ]);
    
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }
    
        $club = Club::firstOrCreate(
            ['name' => $request->input('name')],
            ['city' => $request->input('city')]
        );
    

    
        return redirect()->route('clubs.index');
    }

    public function show($id)
    {
        $club = Club::findOrFail($id);
        $score = $club->score;
        return view('clubs.show', compact('club', 'score'));
    }

    public function edit($id)
    {
    $club = Club::findOrFail($id);
    return view('clubs.edit', compact('club'));
    }

    public function update(Request $request, $id)
{
    $club = Club::findOrFail($id);
    $club->update($request->only(['name', 'city']));

    return redirect()->route('clubs.index')->with('success', 'Club updated successfully');
}

public function destroy($id)
{
    $club = Club::findOrFail($id);
    $club->delete();

    return redirect()->route('clubs.index')->with('success', 'Club deleted successfully');
}

}

resources/views/clubs/create.blade.php
@extends('layouts.content')


@section('content')

<div class="container mt-4">
    <h1>Create Club</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('clubs.store') }}" method="post">
        @csrf

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" name="name" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="city">City:</label>
            <input type="text" name="city" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Save Club</button>
    </form>
</div>

@endsection

resources/views/clubs/edit.blade.php
@extends('layouts.content')

@section('content')

<div class="container mt-4">
    <h1>Edit Club</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('clubs.update', $club->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" name="name" value="{{ $club->name }}" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="city">City:</label>
            <input type="text" name="city" value="{{ $club->city }}" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Update Club</button>
    </form>
</div>

@endsection

resources/views/clubs/index.blade.php
@extends('layouts.content')

@section('content')

<div class="container mt-4">
    <h1>Club List</h1>

    <a href="{{ route('clubs.create') }}" class="btn btn-primary mb-3">Add Club</a>

    @if (count($clubs) > 0)
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>City</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($clubs as $club)
                    <tr>
                        <td>{{ $club->name }}</td>
                        <td>{{ $club->city }}</td>
                        <td>
                            <a href="{{ route('clubs.edit', $club->id) }}" class="btn btn-sm btn-primary">Edit</a>
                            <form action="{{ route('clubs.destroy', $club->id) }}" method="post" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this club?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>No clubs available.</p>
    @endif
</div>

@endsection