routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\StandingsController;
use App\Http\Controllers\MatchController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/master', function () {
    return view('layouts.master');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/clubs', ClubController::class);
Route::resource('/scores', ScoreController::class);
Route::get('/standings', [StandingsController::class, 'index'])->name('standings.index');
Route::get('/matches/create', [MatchController::class, 'create'])->name('matches.create');
Route::resource('/matches', MatchController::class);
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');
// Route::post('/matches/multiple', [MatchController::class, 'storeMultiple'])->name('matches.storeMultiple');

app/Models/Match.php
<?php

// app/Models/Match.php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Match extends Model
{
    use HasFactory;

    protected $fillable = [
        'club_1_id',
        'club_2_id',
        'score',
        'club_1_goals',
        'club_2_goals',
    ];

    // Definisikan relasi ke model Club
    public function club1()
    {
        return $this->belongsTo(Club::class, 'club_1_id');
    }

    public function club2()
    {
        return $this->belongsTo(Club::class, 'club_2_id');
    }
}

app/Http/Controllers/MatchController.php
<?php

namespace App\Http\Controllers;

use App\Models\Match;
use App\Models\Club;
use Illuminate\Http\Request;

class MatchController extends Controller
{
    public function create()
    {
        $clubs = Club::all(); 

        return view('matches.create', compact('clubs'));
    }

    public function store(Request $request)
    {
        $match = Match::create([
            'club_1_id' => $request->club_1_id,
            'club_2_id' => $request->club_2_id,
            'score' => $request->score,
            'club_1_goals' => $request->club_1_goals,
            'club_2_goals' => $request->club_2_goals,
        ]);

        if ($match->club_1_goals > $match->club_2_goals) {
            $club1 = Club::find($match->club_1_id);
            $club2 = Club::find($match->club_2_id);
            $club1->match_win += 1;
            $club1->match_played += 1;
            $club1->match_lose += 0;
            $club1->goals_match_win += $request->club_1_goals;
            $club1->goals_match_lose += 0;
            $club1->points += 3;
            $club2->match_played += 1;
            $club2->match_lose += 1;
            $club2->goals_match_lose += $request->club_2_goals;
            $club1->save();
            $club2->save();
    
        } elseif ($match->club_1_goals < $match->club_2_goals) {
            $club2 = Club::find($match->club_1_id);
            $club1 = Club::find($match->club_2_id);
            $club2->match_win += 1;
            $club2->match_played += 1;
            $club2->match_lose += 0;
            $club2->goals_match_win += $request->club_2_goals;
            $club2->goals_match_lose += 0;
            $club2->points += 3;
            $club1->match_played += 1;
            $club1->match_lose += 1;
            $club1->goals_match_lose += $request->club_1_goals;
            $club1->save();
            $club2->save();

        } else {
            $club1 = Club::find($match->club_1_id);
            $club2 = Club::find($match->club_1_id);
            $club1->points += 1;
            $club2->points += 1;
            $club1->save();
            $club2->save();
        }

        return redirect()->route('matches.index');
    }

    public function index()
    {
        $matches = Match::all();
        return view('matches.index', compact('matches'));
    }

    public function show($id)
    {
        $match = Match::findOrFail($id);
        return view('matches.show', compact('match'));
    }
}

resources/views/matches/create.blade.php
@extends('layouts.content')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create Match</div>

                    <div class="card-body">
                        <form action="{{ route('matches.store') }}" method="POST">
                            @csrf

                            <div class="form-group">
                                <label for="club_1_id">Club 1:</label>
                                <select class="form-control" name="club_1_id" id="club_1_id">
                                    @foreach($clubs as $club)
                                        <option value="{{ $club->id }}">{{ $club->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="club_2_id">Club 2:</label>
                                <select class="form-control" name="club_2_id" id="club_2_id">
                                    @foreach($clubs as $club)
                                        <option value="{{ $club->id }}">{{ $club->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="score">Score:</label>
                                <input type="text" class="form-control" name="score" id="score">
                            </div>

                            <div class="form-group">
                                <label for="club_1_goals">Club 1 Goals:</label>
                                <input type="number" class="form-control" name="club_1_goals" id="club_1_goals">
                            </div>

                            <div class="form-group">
                                <label for="club_2_goals">Club 2 Goals:</label>
                                <input type="number" class="form-control" name="club_2_goals" id="club_2_goals">
                            </div>

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
@endsection

resources/views/matches/index.blade.php
@extends('layouts.content')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Matches</div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Club 1</th>
                                    <th>Club 2</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($matches as $match)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $match->club1->name }}</td>
                                        <td>{{ $match->club2->name }}</td>
                                        <td>
                                            <a href="{{ route('matches.show', $match->id) }}" class="btn btn-primary">View Details</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/matches/show.blade.php
@extends('layouts.content')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Match Details</div>

                    <div class="card-body">
                        <h4>Club 1: {{ $match->club1->name }}</h4>
                        <h4>Club 2: {{ $match->club2->name }}</h4>
                        <p>Score: {{ $match->score }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection